spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/api-entreprise/**


        - id: r2
          uri: http://localhost:9090/
          predicates:
            - Path=/api/**
